# Generated by Django 2.1.2 on 2018-10-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='TypeId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Type'),
        ),
    ]
