# Generated by Django 2.1.2 on 2018-10-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_typeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='TypeId',
            new_name='Type',
        ),
    ]
