# Generated by Django 2.1.2 on 2018-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181022_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.IntegerField(default=0),
        ),
    ]
