# Generated by Django 2.1.2 on 2018-10-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181022_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_point', models.IntegerField(default=0)),
                ('o_points', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
