# Generated by Django 2.1.2 on 2018-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181011_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer_name',
            field=models.CharField(default='No Name', max_length=200),
        ),
    ]
