# Generated by Django 2.1.2 on 2018-10-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_singer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.FileField(default='/home/usman/django/proj2/music/static/music/images/huaweip9bounceringtone-42340.mp3', max_length=500, upload_to=''),
        ),
    ]
