# Generated by Django 2.1.2 on 2018-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
